### ISSUE TITLE
[BUG] 此插件不支持PHP 8.0+

### ISSUE THREAD

**Issue by MFWT** [nkxingxh/MiraiEz#12]
由于PHP 8.0+规定，没有默认值的函数参数必须放在定义的前面（也有可能是直接废弃了默认值这种写法，不是很明白），所以插件在PHP8.0+下运行会抛出错误：

```
在 /home/wwwroot/local.conn/pluginsHelp.php 中的第 92 行处发生错误 (8192) :  Required parameter $config follows optional parameter $configFile
```

而导致无法运行
详见：[StackOverflow - Required parameter $xxx follows optional parameter $yyy](https://stackoverflow.com/questions/65297279/required-parameter-xxx-follows-optional-parameter-yyy)

**Comment by nkxingxh** [comment]
感谢你的反馈，现已使用空数组填充该参数。如发现类似问题，请务必反馈，我将会跟进处理。

**Comment by MFWT** [comment]
多谢修复
